services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: microblog
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Manila
    restart: unless-stopped
    volumes: 
      - db_data:/var/lib/mysql
    networks:
      - microblog

  web:
    build:
      args:
        PHP_MODE: production
      context: .
    depends_on: 
      - db
    restart: unless-stopped
    volumes: 
      - ./:/var/www/html
    ports:
      - "80:80"  # Apache port
      - "8000:8000"  # PHP's built-in server port
    networks:
      - microblog

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
     - "1025:1025"
     - "8025:8025"
    networks:
      - microblog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - microblog

networks:
  microblog:
    driver: bridge

volumes:
  db_data: